var m="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)},n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function p(){p=function(){};n.Symbol||(n.Symbol=t)}var t=function(){var a=0;return function(c){return"jscomp_symbol_"+(c||"")+a++}}();
function u(){p();var a=n.Symbol.iterator;a||(a=n.Symbol.iterator=n.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&m(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return v(this)}});u=function(){}}function v(a){var c=0;return w(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function w(a){u();a={next:a};a[n.Symbol.iterator]=function(){return this};return a}function x(a){u();p();u();var c=a[Symbol.iterator];return c?c.call(a):v(a)}
for(var y=n,A=["Promise"],B=0;B<A.length-1;B++){var C=A[B];C in y||(y[C]={});y=y[C]}
var D=A[A.length-1],E=y[D],G=function(){function a(b){this.c=0;this.i=void 0;this.b=[];var a=this.g();try{b(a.resolve,a.reject)}catch(e){a.reject(e)}}function c(){this.a=null}function f(b){return b instanceof a?b:new a(function(a){a(b)})}if(E)return E;c.prototype.j=function(b){null==this.a&&(this.a=[],this.s());this.a.push(b)};c.prototype.s=function(){var b=this;this.l(function(){b.v()})};var g=n.setTimeout;c.prototype.l=function(b){g(b,0)};c.prototype.v=function(){for(;this.a&&this.a.length;){var b=
this.a;this.a=[];for(var a=0;a<b.length;++a){var e=b[a];delete b[a];try{e()}catch(h){this.u(h)}}}this.a=null};c.prototype.u=function(b){this.l(function(){throw b;})};a.prototype.g=function(){function b(b){return function(d){e||(e=!0,b.call(a,d))}}var a=this,e=!1;return{resolve:b(this.B),reject:b(this.h)}};a.prototype.B=function(b){if(b===this)this.h(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.C(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=
!0;break a;default:d=!1}d?this.A(b):this.m(b)}};a.prototype.A=function(b){var a=void 0;try{a=b.then}catch(e){this.h(e);return}"function"==typeof a?this.D(a,b):this.m(b)};a.prototype.h=function(a){this.o(2,a)};a.prototype.m=function(a){this.o(1,a)};a.prototype.o=function(a,d){if(0!=this.c)throw Error("Cannot settle("+a+", "+d|"): Promise already settled in state"+this.c);this.c=a;this.i=d;this.w()};a.prototype.w=function(){if(null!=this.b){for(var a=this.b,d=0;d<a.length;++d)a[d].call(),a[d]=null;
this.b=null}};var l=new c;a.prototype.C=function(a){var b=this.g();a.f(b.resolve,b.reject)};a.prototype.D=function(a,d){var b=this.g();try{a.call(d,b.resolve,b.reject)}catch(h){b.reject(h)}};a.prototype.then=function(b,d){function e(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(I){q(I)}}:b}var c,q,f=new a(function(a,b){c=a;q=b});this.f(e(b,c),e(d,q));return f};a.prototype["catch"]=function(a){return this.then(void 0,a)};a.prototype.f=function(a,d){function b(){switch(c.c){case 1:a(c.i);
break;case 2:d(c.i);break;default:throw Error("Unexpected state: "+c.c);}}var c=this;null==this.b?l.j(b):this.b.push(function(){l.j(b)})};a.resolve=f;a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(a,c){for(var d=x(b),e=d.next();!e.done;e=d.next())f(e.value).f(a,c)})};a.all=function(b){var c=x(b),e=c.next();return e.done?f([]):new a(function(a,b){function d(b){return function(c){g[b]=c;z--;0==z&&a(g)}}var g=[],z=0;do g.push(void 0),z++,f(e.value).f(d(g.length-
1),b),e=c.next();while(!e.done)})};return a}();G!=E&&null!=G&&m(y,D,{configurable:!0,writable:!0,value:G});function H(a){function c(c){return a.next(c)}function f(c){return a["throw"](c)}return new Promise(function(g,l){function b(a){a.done?g(a.value):Promise.resolve(a.value).then(c,f).then(b,l)}b(a.next())})}
H(function(){function a(){for(;;)switch(c){case 0:F=325,q=2E3,h=500,e=["talks","sprints","tutorials"],d=".typed-text__dynamic",b=document.querySelector(d),l=function(a){return new Promise(function(b){setTimeout(b,a)})},g=function(a,b,c){c=void 0===c?!1:c;return H(function(){function d(d,g){for(;;)switch(e){case 0:f=h/(b.length*(c?2:1)),r=1;case 1:if(!(r<=b.length)){e=3;break}e=4;return{value:l(f),done:!1};case 4:if(1!=d){e=5;break}e=-1;throw g;case 5:a.innerText=b.slice(0,c?b.length-r:r);case 2:r++;
e=1;break;case 3:e=-1;default:return{value:void 0,done:!0}}}var e=0,r,f,g={next:function(){return d(0,void 0)},"throw":function(a){return d(1,a)},"return":function(){throw Error("Not yet implemented");}};u();g[Symbol.iterator]=function(){return this};return g}())},f=function(){H(function(){function a(a,k){for(;;)switch(c){case 0:case 1:h=x(e),f=h.next();case 3:if(f.done){c=5;break}d=f.value;c=6;return{value:l(F),done:!1};case 6:if(1!=a){c=7;break}c=-1;throw k;case 7:return c=8,{value:g(b,d),done:!1};
case 8:if(1!=a){c=9;break}c=-1;throw k;case 9:return c=10,{value:l(q),done:!1};case 10:if(1!=a){c=11;break}c=-1;throw k;case 11:return c=12,{value:g(b,d,!0),done:!1};case 12:if(1!=a){c=13;break}c=-1;throw k;case 13:case 4:f=h.next();c=3;break;case 5:c=1;break;case 2:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,f,h,k={next:function(){return a(0,void 0)},"throw":function(b){return a(1,b)},"return":function(){throw Error("Not yet implemented");}};u();k[Symbol.iterator]=function(){return this};
return k}())},window.addEventListener("DOMContentLoaded",function(){f()}),c=-1;default:return{value:void 0,done:!0}}}var c=0,f,g,l,b,d,e,h,q,F,k={next:function(){return a()},"throw":function(){return a()},"return":function(){throw Error("Not yet implemented");}};u();k[Symbol.iterator]=function(){return this};return k}());